-- CREATE DATABASE users;
CREATE SEQUENCE USERS_SEQUENCE
    start 1
    increment 1
;

CREATE TABLE USERS
(
    ID BIGINT DEFAULT nextval('USERS_SEQUENCE') NOT NULL,

    COINS BIGINT NOT NULL CHECK (COINS>=0),

    COINS_LAST_UPDATE TIMESTAMP NOT NULL,

    NAME varchar(90) NOT NULL,

    PRIMARY KEY (ID)
);
